name: Run Robot Framework Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          if ! command -v google-chrome &> /dev/null; then
            sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
          fi

      - name: Run Robot Framework UI & API tests
        run: |
          robot -d results tests

      - name: Generate HTML Report
        run: |
          pip install robotframework
          rebot --outputdir results --log log.html --report report.html --output output.xml results/output.xml

      - name: Upload test results and HTML report
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results